### ISSUE TITLE
why not use ```Haskell to replace ```?

### ISSUE THREAD

**Issue by LastAvenger** [MnO2/learnyouahaskell-zh#61]
github support the syntax of haskell, why not use it?
if so, I am glad to replace it.

**Comment by MnO2** [comment]
@LastAvenger: No specific reason. I just recently migrate from the legacy formatting syntax to markdown. And the I used regular expression to replace them to ```. If you would love to replace it with ```haskell I would be grateful.

**Comment by LastAvenger** [comment]
ok, I will do it.

**Comment by MnO2** [comment]
@LastAvenger :+1:
