### ISSUE TITLE
A mistake in chap6

### ISSUE THREAD

**Issue by rubyhyd** [MnO2/learnyouahaskell-zh#63]
In section Map and Filter,

"* 的型别为 (Num a) -> a -> a -> a" 
should be modified as
"* 的型别为 (Num a) => a -> a -> a"

I hope I am correct this time. :-)

**Comment by MnO2** [comment]
Fix in 810dfdbdb6a62ffe1dc1229180bbdc4d670208ac. Thanks @rubyhyd
