### ISSUE TITLE
Suitable word of 'Recursion' in simplify Chinese

### ISSUE THREAD

**Issue by vinthony** [MnO2/learnyouahaskell-zh#68]
In chapter 5, 'recursion' is translate to "递回", it's a little weird. In mainland China ,we usually use "递归" other than "递回"  to stand for 'recursion'.

**Comment by MnO2** [comment]
The simplified Chinese version is transcribed from traditional Chinese version with opencc. Once there is a mapping in the opencc dictionary then it could be easily fixed, but apparently "遞迴" => "递归" is not there yet. A workaround for sure is to replace the wrong translation with an editor, but that would make future fix more complicated. That means I have to send a pull request to opencc for this issue.

**Comment by vinthony** [comment]
alright

**Comment by MnO2** [comment]
@vinthony :  I got some time to have a look of this issue. I found that as long as I use tw2sp.json config for opencc, then the recursion is correctly mapped to "递归“. I have pushed a new version to gitbook. Please have a look, thanks.

**Comment by vinthony** [comment]
@MnO2 I have looked these parts of the gitbook，it works.

**Comment by MnO2** [comment]
Great, thanks!
