### ISSUE TITLE
Images are missing

### ISSUE THREAD

**Issue by caasi** [MnO2/learnyouahaskell-zh#90]
現在圖片連結是失效的：

![截圖 2020-05-28 09 29 42](https://user-images.githubusercontent.com/1164470/83088289-e3425c80-a0c5-11ea-95cb-44c5f6ac9c53.png)

**Comment by MnO2** [comment]
It works for me.

![Screenshot 2020-05-31 at 10 25 31 AM](https://user-images.githubusercontent.com/64175/83354806-1a647800-a329-11ea-8633-6e9a32f79134.png)

Are you able to access gitbook CDN from your network where the images are hosted.

https://gblobscdn.gitbook.com/assets%2F-LjUmp_4rLaEvLYs4D0h%2F-LjUmptMINNvnlhyXusA%2F-LjUmrkW5Hh1iMs_baon%2Fbird.png?alt=media

My dig result is as follows:

```
± % dig gblobscdn.gitbook.com                                                                                                                                                                                                                                          !10269

...

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;gblobscdn.gitbook.com.		IN	A

;; ANSWER SECTION:
gblobscdn.gitbook.com.	3600	IN	A	34.107.207.82

```

**Comment by caasi** [comment]
Bad Bagder :|

![截圖 2020-06-01 02 28 27](https://user-images.githubusercontent.com/1164470/83359868-b6d15d80-a3af-11ea-9bee-89940229cad5.png)
